// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAO5rGnnBNepOO7qpcvMQWEN6n0PRpFqNo',
    appId: '1:918972972138:web:706dc0ec074183a1325e13',
    messagingSenderId: '918972972138',
    projectId: 'amorra-bd69f',
    authDomain: 'amorra-bd69f.firebaseapp.com',
    storageBucket: 'amorra-bd69f.firebasestorage.app',
    measurementId: 'G-H6B9L6EHGC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_F7mkrFBglandbPoCWTbxbiDZ3Tsob34',
    appId: '1:918972972138:android:5ea27eb88e27c05e325e13',
    messagingSenderId: '918972972138',
    projectId: 'amorra-bd69f',
    storageBucket: 'amorra-bd69f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNJ71KT1OBvwjkNoR44XOq1ZZ44qS68zs',
    appId: '1:918972972138:ios:37cf5f4756ff112a325e13',
    messagingSenderId: '918972972138',
    projectId: 'amorra-bd69f',
    storageBucket: 'amorra-bd69f.firebasestorage.app',
    iosBundleId: 'com.example.amorra',
  );
}
