// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9AR1kTcMbQctDCwG2esCHUEoPxyB4MBQ',
    appId: '1:39064571782:web:8c3cc79d8ca36d60876607',
    messagingSenderId: '39064571782',
    projectId: 'amorraai',
    authDomain: 'amorraai.firebaseapp.com',
    storageBucket: 'amorraai.firebasestorage.app',
    measurementId: 'G-DF3JNN2WM4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUYjqMy_mSVKzk4-lEiYZ8ezUDcMahdPE',
    appId: '1:39064571782:android:226cad07c7231478876607',
    messagingSenderId: '39064571782',
    projectId: 'amorraai',
    storageBucket: 'amorraai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmydeJI0i9vY9SWzNBMyEQXd_0zI2xIwQ',
    appId: '1:39064571782:ios:40b8b197a7d3d007876607',
    messagingSenderId: '39064571782',
    projectId: 'amorraai',
    storageBucket: 'amorraai.firebasestorage.app',
    iosBundleId: 'com.example.amorra',
  );
}
